### ISSUE TITLE
Syntax question

### ISSUE THREAD

**Issue by mwpastore** [scottwater/rack-pooledthrottle#1]
The syntax given for Dalli in the README is:

```ruby
use Rack::Throttle::Interval, max: 10, ttl: 3600, pool: $mc_pool
```

But I can't get that to work; it says: `uninitialized constant Rack::Throttle (NameError)`

However, this works:

```ruby
use Rack::PooledThrottle::MemcachedThrottle, max: 10, ttl: 3600, pool: $mc_pool
```

Is that the right syntax?

**Comment by scottwater** [comment]
That is correct. Looks like I made a mistake copying and pasting. I will get this fixed shortly. Thanks!
